language: python
python: "3.3"
install:
  - pip install codecov
  - pip install coverage
script:
  - python -m unittest discover -v ./tests/
  - coverage run ./tests/test.py
after_success:
  - codecov
before_install:
  - openssl aes-256-cbc -K $encrypted_38c367689ba7_key -iv $encrypted_38c367689ba7_iv
    -in deploy_rsa.enc -out deploy_rsa -d
addons:
  # add our deploy server to known hosts
  ssh_known_hosts: moon.scs.ryerson.ca

before_deploy:
  - openssl aes-256-cbc -K $encrypted_38c367689ba7_key -iv $encrypted_38c367689ba7_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
# deploy using rsync or scp
# setup ENV ($) variables in the web interface
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet
    ${TRAVIS_BUILD_DIR}/build
    ${DEPLOY_USER}@${DEPLOY_SERVER}:/home/avm/courses/cps847/${DEPLOY_USER}/
  on:
branch: master
